apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-nginx-helm
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/dev/myapp-nginx-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: myapp-nginx-helm
  targetNamespace: default
  timeout: 2m
