apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myapp-nginx-helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kiran-2407/Flux-Linux-RHEL9.2.git
  ref:
    branch: main
  ignore: |
    # exclude everything
    /*
    # include just the folder we care about
    !/clusters/dev/myapp-nginx-helm/
