apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: myapp-update
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: bot@users.noreply.github.com
        name: flux-bot
      messageTemplate: |
        auto update image to {{range .Updated.Images}}{{.NewTag}}{{end}}
    push:
      branch: main
  update:
    path: ./clusters/minikube/apps/nginx
    strategy: Setters
