apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  path: "./clusters/minikube/apps/nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
