apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-app
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: bitnami/nginx
    newName: bitnami/nginx
    newTag: 1.25.0  # this gets updated by ImageAutomation
