---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-bitnami
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 15.3.1
  interval: 5m0s
  releaseName: nginx-bitnami
  targetNamespace: default