apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp-nginx-helm
  namespace: default
spec:
  releaseName: myapp-nginx-helm
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.3.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
    service:
      type: LoadBalancer
