# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp-nginx
  namespace: default
spec:
  interval: 1m
  releaseName: myapp-nginx
  chart:
    spec:
      chart: nginx
      version: 15.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 3
    service:
      type: LoadBalancer
      port: 80
