apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-image-controllers
  namespace: flux-system
spec:
  releaseName: flux-image-controllers
  interval: 5m
  chart:
    spec:
      chart: flux2
      sourceRef:
        kind: HelmRepository
        name: flux-system
        namespace: flux-system
      version: "2.*.*"
  values:
    components:
      - source-controller
      - kustomize-controller
      - helm-controller
      - notification-controller
      - image-automation-controller
      - image-reflector-controller
